'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
"""
        :type s: str
        :type t: str
        :rtype: str
        """
class Solution(object):
    def findTheDifference(self, s, t):
        old = []
        for letter in t:
            old.append(letter)
        for letter in s:
            old.remove(letter)
        return old[0]

if __name__ == "__main__":
	sol = Solution()
	s = "apple"
	t = "ledpap"
	print(sol.findTheDifference(s,t))
